import 'reflect-metadata';

import { INestApplication } from '@nestjs/common';
import request, { SuperTest, Test } from 'supertest';

import { TaskBreakdownRequestDto } from '../src/modules/planning/dto/task-breakdown-request.dto';
import { GeminiService } from '../src/modules/planning/service/gemini.service';
import { GeminiGenerateContentResponse } from '../src/modules/planning/types/gemini.types';

describe('PlanningController (e2e)', () => {
  let app: INestApplication;
  let api: SuperTest<Test>;
  let geminiService: GeminiService;

  beforeAll(() => {
    app = global.app!;
    api = request(app.getHttpServer());
    geminiService = app.get(GeminiService);
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  const requestPayload: TaskBreakdownRequestDto = {
    summary: 'Launch new website',
    preferredSubtaskCount: 3,
  };

  it('returns subtasks generated by Gemini with usage metadata', async () => {
    const llmResponse: GeminiGenerateContentResponse = {
      candidates: [
        {
          content: {
            parts: [
              {
                text: '1. Design wireframes\n2. Implement frontend\n3. Run QA',
              },
            ],
          },
        },
      ],
      usageMetadata: {
        promptTokenCount: 50,
        candidatesTokenCount: 120,
        totalTokenCount: 170,
      },
    };

    jest
      .spyOn(geminiService, 'generateContent')
      .mockResolvedValueOnce(llmResponse);

    const response = await api
      .post('/api/v1/planning/task-breakdown')
      .send(requestPayload)
      .expect(200);

    expect(response.body.subtasks).toEqual([
      'Design wireframes',
      'Implement frontend',
      'Run QA',
    ]);
    expect(response.body.usage).toEqual(
      expect.objectContaining({ totalTokens: 170 }),
    );
    expect(geminiService.generateContent).toHaveBeenCalledWith(
      expect.stringContaining('Primary task: Launch new website'),
    );
  });

  it('falls back to heuristic subtasks when Gemini returns no candidates', async () => {
    jest.spyOn(geminiService, 'generateContent').mockResolvedValueOnce({
      candidates: [],
    } as GeminiGenerateContentResponse);

    const response = await api
      .post('/api/v1/planning/task-breakdown')
      .send(requestPayload)
      .expect(200);

    expect(response.body.subtasks).toHaveLength(6);
    expect(response.body.subtasks[0]).toContain('Clarify success metrics');
    expect(response.body.usage.totalTokens).toBe(0);
  });

  it('enforces validation rules for planning requests', async () => {
    const response = await api
      .post('/api/v1/planning/task-breakdown')
      .send({ summary: 'abc', preferredSubtaskCount: 50 })
      .expect(422);

    expect(response.body.statusCode).toBe(422);
    expect(response.body.message).toBeDefined();
  });
});
