export enum ExceptionName {
  INCORRECT_SIGNIN = 'INCORRECT_SIGNIN',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_EXCEPTION = 'INTERNAL_EXCEPTION',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  CONFLICT = 'CONFLICT',
  EXTERNAL_SERVICE_EXCEPTION = 'EXTERNAL_SERVICE_EXCEPTION',
}
